### ISSUE TITLE
Textures of the crystals not working.

### ISSUE THREAD

**Issue by shadowpt11** [tyap-lyap/artifality#10]
The textures aren't showing up currently, at least for me.
They show up as a purple and black cubes, all of the crystals are.
Is there a fix or am I just unlucky?

**Comment by PinkGoosik** [comment]
huh weird, can you provide your mod list?

**Comment by MaNDaNgEr** [comment]
I also have the same problem what to do ??

**Comment by PinkGoosik** [comment]
> I also have the same problem what to do ??

Provide your mod list please

**Comment by MaNDaNgEr** [comment]
oh it is fixed it was because of dashloader mod

**Comment by PinkGoosik** [comment]
dashloader is incompatible with bclib huh makes sense https://github.com/alphaqu/DashLoader/issues/54

**Comment by PinkGoosik** [comment]
fixed
