### ISSUE TITLE
[Crash] random unknown crash.

### ISSUE THREAD

**Issue by SylisMC** [tyap-lyap/artifality#6]
I kept getting this crash with my modlist issue went away when remiving the mod, im not sure whats causing the conflict but i figured id leave the report here. all the information you need should be in there

mc 1.17.1

https://bytebin.lucko.me/QKZhNpJwY8

**Comment by PinkGoosik** [comment]
Just found out that this crash caused by incompatibility with pehkui mod

**Comment by SylisMC** [comment]
ahh, well that's at least good to know, I had to mess with it for about an hour trying to figure it out, but it can sometimes take a while for the crash to happen, so i ended up getting frustrated and quit trying to narrow down the mods list haha sorry about that

**Comment by PinkGoosik** [comment]
yeah that's pretty weird crash i can't really figure out how to fix it

**Comment by MoriyaShiine** [comment]
Oh I just got an issue report mentioning this lol (https://github.com/MoriyaShiine/bewitchment/issues/193), I can PR a fix tomorrow

**Comment by Virtuoel** [comment]
This has (potentially) been resolved on Pehkui's end and a (hopefully) fixed version will be released in a few days.

**Comment by PinkGoosik** [comment]
fixed in 0.3.4
