### ISSUE TITLE
Suggestions: Slowfall from the Balloon should be more consistent with other mechanics.

### ISSUE THREAD

**Issue by EmoBubbleGum** [tyap-lyap/artifality#8]
Shift is naturally the key to go down. In creative flight, in other slowfall enchantments, shift always lowers you/cancels slowfall. It feels very unnatural to use shift to slow myself.  it also clashes pretty hard with certain flying abilities, or when you are a specter wraithing (from origins mod) trying to go down, but constantly getting slowed.

Your best bet is to make the slowfall an innate property, and possibly a hotkey for other situations where you dont want it at all

**Comment by PinkGoosik** [comment]
balloon got reworked in 0.4
